#!/usr/bin/env bash

# Install 'dotfiles-bash' from 'https://github.com/adrfer/dotfiles-bash.git'
echo "=> Installing 'dotfiles-bash'..."
bash <(curl -sL https://raw.github.com/adrfer/dotfiles-bash/master/install) && source ~/.bash_profile

# Install 'dotfiles-readline' from 'https://github.com/adrfer/dotfiles-readline.git'
echo "=> Installing 'dotfiles-readline'..."
bash <(curl -sL https://raw.github.com/adrfer/dotfiles-readline/master/install)